"""game_platform

Revision ID: 2cbb4c8a2979
Revises: c36f5733b446
Create Date: 2025-09-03 21:38:41.629855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cbb4c8a2979"
down_revision: Union[str, None] = "c36f5733b446"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("platform", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "platform")
    # ### end Alembic commands ###
