"""game time tags

Revision ID: c36f5733b446
Revises: ba5157ada780
Create Date: 2025-05-16 15:58:28.519686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c36f5733b446"
down_revision: Union[str, None] = "ba5157ada780"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("create_datetime", sa.DateTime(), nullable=True))
    op.add_column(
        "game", sa.Column("first_post_datetime", sa.DateTime(), nullable=True)
    )
    op.add_column("game", sa.Column("done_datetime", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "done_datetime")
    op.drop_column("game", "first_post_datetime")
    op.drop_column("game", "create_datetime")
    # ### end Alembic commands ###
