"""filters in user

Revision ID: 00287c00a337
Revises: b6ea887326b5
Create Date: 2025-10-29 17:45:01.051471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "00287c00a337"
down_revision: Union[str, None] = "b6ea887326b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "filters", sa.JSON(), nullable=False, server_default=text("'{}'::json")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "filters")
    # ### end Alembic commands ###
