"""reviews init

Revision ID: 6ac2b908f037
Revises: cb1561cf5e67
Create Date: 2025-03-17 20:44:06.340951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ac2b908f037"
down_revision: Union[str, None] = "cb1561cf5e67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.BIGINT(), nullable=False),
        sa.Column("to_user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "receiver_type",
            sa.Enum("player", "dm", name="reviewreceivertypeenum"),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["from_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_from_user_id"),
        "review",
        ["from_user_id", "to_user_id", "receiver_type"],
        unique=True,
    )
    op.create_index(
        op.f("ix_review_to_user_id"),
        "review",
        ["to_user_id", "receiver_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_to_user_id"), table_name="review")
    op.drop_index(op.f("ix_review_from_user_id"), table_name="review")
    op.drop_table("review")
    # ### end Alembic commands ###
