"""game_is_update

Revision ID: a5176956f3d0
Revises: 2cbb4c8a2979
Create Date: 2025-09-08 22:16:07.176498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5176956f3d0"
down_revision: Union[str, None] = "2cbb4c8a2979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game",
        sa.Column("is_update", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.execute(
        "UPDATE game SET is_update = true "
        "where DATE(last_update) != DATE(first_post_datetime) and done is not true"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "is_update")
    # ### end Alembic commands ###
