"""feedback_message

Revision ID: 78bfe9674969
Revises: 6ac2b908f037
Create Date: 2025-05-15 13:43:34.583486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78bfe9674969"
down_revision: Union[str, None] = "6ac2b908f037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.BIGINT(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("create_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback_message")
    # ### end Alembic commands ###
