"""game_application_message_id

Revision ID: 971f75b3d2f3
Revises: a5176956f3d0
Create Date: 2025-09-14 11:43:56.645708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "971f75b3d2f3"
down_revision: Union[str, None] = "a5176956f3d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_application", sa.Column("message_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_application", "message_id")
    # ### end Alembic commands ###
