"""unchangeable reviews

Revision ID: e62f8a9a69f8
Revises: 00287c00a337
Create Date: 2026-02-08 11:58:04.602677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e62f8a9a69f8"
down_revision: Union[str, None] = "00287c00a337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review",
        sa.Column("unchangeable", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "unchangeable")
    # ### end Alembic commands ###
