"""init

Revision ID: a3f79e97be14
Revises: 
Create Date: 2024-11-19 16:28:54.622114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3f79e97be14"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("user_type", sa.SMALLINT(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("registered", sa.Boolean(), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("creator_id", sa.BIGINT(), nullable=False),
        sa.Column("group_id", sa.BIGINT(), nullable=True),
        sa.Column("post_id", sa.BIGINT(), nullable=True),
        sa.Column("format", sa.SMALLINT(), nullable=True),
        sa.Column("type", sa.SMALLINT(), nullable=True),
        sa.Column("system", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("min_players", sa.SMALLINT(), nullable=True),
        sa.Column("max_players", sa.SMALLINT(), nullable=True),
        sa.Column("free", sa.Boolean(), nullable=True),
        sa.Column("min_age", sa.SMALLINT(), nullable=True),
        sa.Column("max_age", sa.SMALLINT(), nullable=True),
        sa.Column("time", sa.String(), nullable=True),
        sa.Column("tech_requirements", sa.String(), nullable=True),
        sa.Column("other_requirements", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_member",
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "game_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_member")
    op.drop_table("game")
    op.drop_table("user")
    op.drop_table("city")
    # ### end Alembic commands ###
